test: fix tests for 32-bit platforms
(* 3840 2160 3) bytes is more than 16Mbytes, which is the hard limit
in CHICKEN for 32-bit platforms. This fix cheats by making the test
image smaller.

This should hopefully fix
http://salmonella-linux-x86.call-cc.org/chicken-4-debugbuild/gcc/linux/x86/2018/06/09/salmonella-report/test/stb-image.html
which says:

    '/home/chicken/salmonella/build/salmonella-run-publish/chicken/bin/csi' -script run.scm < /dev/null 2>&1
    read-image 2x2 grayscale png ......................................... [ PASS]
    load-image 2x2 grayscale tga ......................................... [ PASS]
    load-image-info 2x2 grayscale tga .................................... [ PASS]
    read-image-info 2x2 grayscale tga ....................................
    Error: out of range
    24883200
    16777215

A more ambitious fix would allow an option to allow custom memory
allocations perhaps (malloced memory in C obviously doesn't have the
16M limitation).